[package]
name = "yaud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.19", features = ["macros", "multipart"] }
cfg-if = "1.0.0"
getset = "0.1.2"
lazy_static = "1.4.0"
schemars = { version = "0.8.12", features = ["chrono"] }
serde = { version = "1.0.176", features = ["derive"] }
serde_json = "1.0.104"
surrealdb = "1.0.0-beta.11"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.3", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
version-compare = "0.1.1"

[dev-dependencies]
axum-test-helper = { version = "0.3.0", features = ["withouttrace", "cookies"] }
nanoid = "0.4.0"
