[package]
name = "yaud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aide = { version = "0.11.0", features = ["redoc", "axum", "axum-extra", "macros"] }
axum = { version = "0.6.19", features = ["macros", "multipart"] }
axum-jsonschema = { version = "0.6.0", features = ["aide"] }
schemars = { version = "0.8.12", features = ["chrono"] }
serde = { version = "1.0.176", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.3", features = ["fs", "tracing", "cors"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

async-trait = "0.1.72"
axum-extra = "0.7.5"
axum-macros = "0.3.8"
getset = "0.1.2"
serde_json = "1.0.104"
thiserror = "1.0.44"
tracing = "0.1.37"