[package]
name = "yaud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aide = { version = "0.11.0", features = ["redoc", "axum", "axum-extra-cookie", "macros"] }
axum = { version = "0.6.19", features = ["macros", "multipart"] }
axum-jsonschema = { version = "0.6.0", features = ["aide"] }
axum-test-helper = { version = "0.3.0", features = ["withouttrace", "cookies"] }
schemars = { version = "0.8.12", features = ["chrono"] }
serde = { version = "1.0.176", features = ["derive"] }
surrealdb = "1.0.0-beta.11"
tokio = { version = "1.29.1", features = ["full"] }
tower-http = { version = "0.4.3", features = ["fs", "tracing", "cors"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

axum-macros = "0.3.8"
cfg-if = "1.0.0"
chrono = "0.4.26"
getset = "0.1.2"
lazy_static = "1.4.0"
nanoid = "0.4.0"
serde_json = "1.0.104"
thiserror = "1.0.44"
tracing = "0.1.37"
version-compare = "0.1.1"
